//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONFw.EntityClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int Id { get; set; }
        public string DescriptionContent { get; set; }
        public string UserDisplayName { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<int> TempleId { get; set; }
    
        public virtual TempleTable TempleTable { get; set; }
    }
}
