//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONFw.EntityClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryRequest
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public string RequestBy { get; set; }
        public string RequestType { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Status { get; set; }
        public string Key1 { get; set; }
        public string Key2 { get; set; }
    }
}
