//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONFw.EntityClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdolMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdolMaster()
        {
            this.TempleIdolMappings = new HashSet<TempleIdolMapping>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> IdolTypeId { get; set; }
    
        public virtual IdolType IdolType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempleIdolMapping> TempleIdolMappings { get; set; }
    }
}
